# Site settings
title: YANG WANG | 汪洋
email: yang.wang.dec@gmail.com
twitter_username: "@iamyangwang"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yangwang.info/" # the base hostname & protocol for your site
github_username: wangyangwang

# Build settings
markdown: kramdown
