# Site settings
title: THE INTROPSECTION GAME
# baseurl: "/theintrospectiongame.com" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
